mysite/mysite/urls.py
from django.contrib import admin
from django.urls import include, path
from simple_investing import views

urlpatterns = [
    path('admin/', admin.site.urls),      
    path('', include('simple_investing.urls')), #Application 
    path('', include('django.contrib.auth.urls')),
    path('accounts/', include('allauth.urls')), 
    # path('avatar/', include('avatar.urls')),    
    
]

mysite/simple_investing/urls.py
from django.urls import path
from django.views.generic import TemplateView
from . import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
app_name = 'simple_investing'

urlpatterns = [
    path('', TemplateView.as_view(template_name='simple_investing/main.html')),
    path('concepts/', TemplateView.as_view(template_name='simple_investing/concepts.html')),
    path('create_comp/', views.create_comp, name='create_company'),
    path('companies_list/', views.companies_list, name='companies_list'),
    path('details/<int:pk>/', views.detail_comp, name='company_details'),
    path('update_comp/<int:pk>/', views.update_company, name='update_company'),
    path('delete_comp/<int:pk>/', views.delete_company, name='delete_company'),
    path('register_user/', views.register_page, name='register'),
    path('api_y/<company_symbol>/', views.api_y, name= 'yahoo_api'),
    path('symbol/', views.symbol, name= 'symbol'),          

]

urlpatterns += staticfiles_urlpatterns()

mysite/simple_investing/models.py
from django.db import models
from django.contrib.auth.models import User
import decimal
from decimal import Decimal

# Create your models here.

class Company(models.Model):
    #Link to User model
    user = models.ForeignKey(User, on_delete=models.CASCADE, null= True)
    #Company data    
    company_name = models.CharField(max_length=100)
    outstanding_shares = models.IntegerField()
    share_price = models.DecimalField(max_digits= 5, decimal_places=2)
    revenue = models.IntegerField()
    expenses = models.IntegerField()
    total_assets = models.IntegerField()
    total_liabilities = models.IntegerField()
    current_assets = models.IntegerField()
    current_liabilities = models.IntegerField()
    operating_cashflows = models.IntegerField()
    capex = models.IntegerField()    
    
    #Date of creation
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now= True)    
        
    def __str__(self):
        return self.company_name

    #Company methods        
    def net_income(self):        
        return self.revenue - self.expenses

    def net_assets(self):
        return self.total_assets - self.total_liabilities

    def price_to_earnings(self):
        try:
            return round(self.net_income() / self.outstanding_shares, 2)
        except:
            return 0
    def return_on_equity(self):
        try:
            return round(self.net_income() / self.net_assets(), 2) 
        except:
            return 0
    def debt_to_equity(self):
        try:
            return round(self.total_liabilities / self.net_assets(), 2)
        except:
            return 0
    def current_ratio(self):
        try:
            return self.current_assets / self.current_liabilities
        except:
            return 0
    def free_cashflow(self):
        return self.operating_cashflows - self.capex # net cash from operating activities - capex

    def market_cap(self):
        return self.share_price * self.outstanding_shares 

    def price_to_sales(self):
        try:
            return round(self.market_cap() / self.revenue , 2)
        except:
            return 0
    def book_value_per_share(self):
        try:
            result = decimal.Decimal(self.net_assets() / self.outstanding_shares)
            return result.quantize(Decimal('0.01'))
        except:
            return 0                            

    def price_to_book(self):
        try:
            return round(self.share_price / self.book_value_per_share(),2)
        except:
            return 0    

mysite/simple_investing/forms.py
from django import forms
from django.forms import ModelForm
from simple_investing.models import Company
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class CompanyForm(ModelForm):
    class Meta:
        model = Company
        fields = ('company_name', 'outstanding_shares', 'share_price', 'revenue', 'expenses', 'total_assets','total_liabilities', 'current_assets','current_liabilities', 'operating_cashflows', 'capex')
        widgets = {
            'company_name':forms.TextInput(attrs={'class': 'form-control', 'placeholder' : 'Company name'}),
            'outstanding_shares':forms.NumberInput(attrs={'class': 'form-control', 'placeholder' : 'Shares outstanding'}),
            'share_price':forms.NumberInput(attrs={'class': 'form-control', 'placeholder' : 'Share price'}),
            'revenue':forms.NumberInput(attrs={'class': 'form-control', 'placeholder' : 'Revenue'}),
            'expenses':forms.NumberInput(attrs={'class': 'form-control', 'placeholder' : 'Expenses'}),
            'total_assets':forms.NumberInput(attrs={'class': 'form-control', 'placeholder' : 'Total Assets'}),
            'total_liabilities':forms.NumberInput(attrs={'class': 'form-control', 'placeholder' : 'Total Liabilities'}),
            'current_assets' :forms.NumberInput(attrs={'class': 'form-control', 'placeholder' : 'Current Assets'}),
            'current_liabilities':forms.NumberInput(attrs={'class': 'form-control', 'placeholder' : 'Current Liabilities'}),
            'operating_cashflows':forms.NumberInput(attrs={'class': 'form-control', 'placeholder' : 'Operating Cashflows'}),
            'capex':forms.NumberInput(attrs={'class': 'form-control', 'placeholder' : 'Capital Expenditure'}),            
        }


class UserForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')


class UserLogin(ModelForm):
    class Meta:
        model = User
        fields= ('username', 'password')

class CompanySymbol(forms.Form):
    company_symbol = forms.CharField(label='Company symbol', max_length=10,widget=forms.TextInput(attrs={'class': 'form-control','placeholder': 'Company symbol'}))
    

mysite/simple_investing/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse, HttpResponseRedirect
from .forms import CompanyForm, UserForm, UserLogin,CompanySymbol
from django.views import View
from .models import Company
from django.views.generic import ListView
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages
from django.contrib.auth import authenticate, login
from django.contrib.auth.models import User
import requests, json

def create_comp(request):      
    form = CompanyForm()
    if request.method == 'POST':
        print(request.POST)
        form = CompanyForm(request.POST)  
        user = request.user      
        if form.is_valid():                       
            instance = form.save(commit=False)
            instance.user = user
            instance.save()
            return HttpResponseRedirect('http://127.0.0.1:8000/companies_list/')           
    else:          
        context = {'form': form}    
        return render(request, 'simple_investing/create_company.html', context)    

def companies_list(request):
    companies = Company.objects.all()
    context = {'companies' : companies} 
    return render(request, 'simple_investing/companies_list.html',context)

def detail_comp(request, pk):    
    company_obj = Company.objects.get(id=pk)
    context = {'company' : company_obj} 
    return render(request, 'simple_investing/detail.html',context)


def update_company(request,pk):
    company_obj = Company.objects.get(id=pk)
    form = CompanyForm(instance=company_obj)
    if request.method == 'POST':
        form = CompanyForm(request.POST, instance=company_obj)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect('http://127.0.0.1:8000/companies_list/')
    else:
        context = {'form' : form}
        return render(request, 'simple_investing/create_company.html',context)

def delete_company(request,pk):
    company_obj = Company.objects.get(id=pk)    
    if request.method == 'POST':
        company_obj.delete()
        return HttpResponseRedirect('http://127.0.0.1:8000/companies_list/')
    
    else:
        context = {'company' : company_obj}
        return render(request, 'simple_investing/delete_company.html',context)    

def register_page(request):
    form = UserForm
    if request.method == 'POST':
        form = UserForm(request.POST)
        if form.is_valid():
            form.save()            
            return HttpResponseRedirect('http://127.0.0.1:8000/login/')    
    else:
        context = {'form' : form}
        return render(request,'simple_investing/register.html', context)

def api_y(request, company_symbol):    
    url = "https://rest.yahoofinanceapi.com/v6/finance/quote"
    querystring = {"symbols":"{},BTC-USD,EURUSD=X".format(company_symbol)}
    headers = {
    'x-api-key': "duF5YZeWnp1qO62u9g5AI8t6RUjLXTCc4JwDClLx"    
    }
    response = requests.request("GET", url, headers=headers, params=querystring)    
    dic_json = json.loads(response.text) #create a json dictionary in order to grab values
    company = dic_json['quoteResponse']['result'][0] #enter the data of the company by indexing 
    is_company= True
    if 'displayName' not in company: #check to see if there was a retrieval of the company.
        is_company= False            #if false, print a message to re enter the ticket symbol.
    
    context = {'company' : company, 'is_company' : is_company}
    return render(request,'simple_investing/yahoo_api.html', context )

def symbol(request):
    form = CompanySymbol
    if request.method == 'POST':
        form = CompanySymbol(request.POST)
        print(request.POST)
        if form.is_valid():
            company_symbol = form.cleaned_data['company_symbol']
            return HttpResponseRedirect('http://127.0.0.1:8000/api_y/'+company_symbol+'/')
    else:
        context = {'form' : form}
        return render(request,'simple_investing/symbol.html',context )




mysite/simple_investing/templates/simple_investing/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>    
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="stylesheet"  href="{%  static  'css/simple_investing.css'  %}">
    <title> {% block title %} Simple Investing {% endblock title %}</title>    
  </head>
  <body>       
    <div id="navbar">
      <nav class="navbar navbar-expand-lg navbar navbar-dark">
        <div class="container-fluid">
          <img src="{% static '/media/si_logo5.png' %}" width=45 height= 50  style="padding-right: 6px;">
          <a class="navbar-brand" href="http://127.0.0.1:8000/">Simple Investing</a>          
          <div class="collapse navbar-collapse" id="navbarSupportedContent">      
            <ul class="navbar-nav mr-auto">              
              <li class="nav-item">
                <a class="nav-link" href="http://127.0.0.1:8000/concepts">Concepts</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'simple_investing:companies_list' %}">Portfolio</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'simple_investing:create_company' %}">Add Company</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="http://127.0.0.1:8000/symbol/">Ticker symbol</a>
              </li>
              {% if not user.is_authenticated %}
              <li class="nav-item">
                <a class="nav-link" href="http://127.0.0.1:8000/accounts/login">Login</a>
              </li>              
              <li class="nav-item">
                <a class="nav-link" href="http://127.0.0.1:8000/accounts/signup">Sign up</a>
              </li>              
              {% endif %}                     
            </ul>
              {% if user.is_authenticated %}
            <ul class="navbar-nav ms-auto">
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">                                              
                  {{user}}                  
                  {% endif %}
                </a>
                <ul class="dropdown-menu" style="right: 0cm; left:auto;" aria-labelledby="navbarDropdownMenuLink">              
                  <li><a class="dropdown-item" href="http://127.0.0.1:8000/logout">Logout</a></li>                 
                </ul>
              </li>         
            </ul>          
          </div>
        </div>      
      </nav>
      <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>   
    </div>
    <div id="subtitle">
      <h2 class="display-4">{%block subtitle %} {% endblock subtitle %}</h2>
    </div>
    <div id= "content">
      {% block content %} {% endblock content %}
    </div>
    <footer>
      <div class="logo-container">
        <img src="{% static '/media/si_logo2.png' %}">        
      </div>
    </footer>           
  </body> 
</html>    

mysite/simple_investing/templates/simple_investing/companies_list.html
{% extends 'simple_investing/base.html' %}
{% block subtitle %}Companies that you are following{% endblock subtitle%}
{% block content %}    
    <hr>
    {% if user.is_authenticated %}       
        <p>If you want to learn the fundamentals of each company just click! otherwise <a href="{%url 'simple_investing:create_company'%}"> add</a>  a company to your portfolio!</p>
    {% else %}
        <p>In order to access your portfolio <a href = "/accounts/login/">login.</a></p>
    {% endif %}    
    {% for company in companies %} <!-- iterating over all of the companies in the database.-->
        {% if company.user == user %} <!-- selecting the companies that a user has created.-->
        <p><ul class="list-unstyled"><a href="{% url 'simple_investing:company_details' company.id %}" class="btn btn-outline-success"></button>{{company}}</a></p>
        {% endif %}
    {% endfor %}   
{% endblock content %}

mysite/simple_investing/templates/simple_investing/concepts.html
{% extends 'simple_investing/base.html' %}
{% block subtitle %} Investing Concepts {% endblock subtitle %}
{% block content %}
    <hr>  
    <p><font size="+1">What is <strong>investing?</strong></font></p>
    <p>In the pursuit of simplicity, one can say that <strong><i>to invest</i></strong> is to allocate money with the expectation of a positive <i>return</i> (<strong>profit</strong>) in the future. To explore this concept further you can visit: <a href = https://en.wikipedia.org/wiki/Investment> Wikipedia</a> or <a href = https://www.investopedia.com/terms/i/investment.asp> Investopedia.</a></p>
    <p>Taking into account the aforementioned definition, we can assume that there are different investing vehicles (<strong>assets or financial instruments</strong>) that one can choose.</p>
    <p>In this website we will focus on investing in <strong>public businesses</strong> (commonly known as <strong>stocks</strong>).</p>    
    <br>
    <p><font size="+1">What is a <strong>stock?</strong></font> </p>
    <p> A stock is all of the <i>shares</i> (<strong>fractions</strong>) into which ownership of a corporation (<strong><i>business</i></strong>) is divided into. In other words, one can say that<strong><i> by owning a stock, one owns a fraction of a business</i></strong>.</p>
    <p>If we own a great business (<strong><i>stock</i></strong>) that generates handsome profits, the <strong><i>stock price</i></strong> will follow. Conversley, if we own a bad business (<strong>stock</strong>) that loses money, the stock price will follow accordingly.</p>
    <p>In that regard, there are different <strong><i>investing metrics</i></strong> (investing metrics) that we can use to <strong><i>evaluate, meassure</i></strong> the fundamentals of any public business that caught our attention.</p>
    <br>            
    <p><font size="+1">What are the <strong>fundamentals</strong> of  business?</font> </p>
    <p>The <i>fundamentals</i> are the intrinsic characteristics of the business. In simple words, its revenues, assets, liabilities, etc.</p>
        
    <p>There are different metrics we can use to analyze the fundamentals of any public company. These metrics are ratios. A ratio is relationship between two concepts.</p>  
    <p>In this website, we will use some of the most conventional ones:</p>
        
    <ul>   
        <li><p>Free cashflow. (FCF)<a href = https://www.investopedia.com/terms/f/freecashflow.asp class="btn btn-outline-success"></button> Keep learning!</a></p></li>
        <li><p>Return on equity. (ROE)<a href = https://www.investopedia.com/terms/r/returnonequity.asp class="btn btn-outline-success"></button>Keep learning!</a></p></li>
        <li><p>Price to earnings. (P/E)<a href = https://www.investopedia.com/terms/p/price-earningsratio.asp class="btn btn-outline-success"></button> Keep learning!</a></p></li>
        <li><p>Debt to equity. (D/E)<a href = https://www.investopedia.com/terms/d/debtequityratio.asp class="btn btn-outline-success"></button> Keep learning!</a></p></li>
        <li><p>Current Ratio.  (CR)<a href = https://www.investopedia.com/terms/c/currentratio.asp class="btn btn-outline-success"></button> Keep learning! </a></p></li>
        <li><p>Price to sales.  (CR)<a href = https://www.investopedia.com/articles/fundamental/03/032603.asp class="btn btn-outline-success"></button> Keep learning! </a></p></li>
        <li><p>Net Income. (NI) <a href = https://www.investopedia.com/terms/n/netincome.asp class="btn btn-outline-success"></button> Keep learning!</a></p></li>
        <li><p>Share holders Equity. (Se) <a href = https://www.investopedia.com/terms/s/shareholdersequity.asp class="btn btn-outline-success"></button> Keep learning! </a></p></li>
        <li><p>Market Capitalization. <a href = https://www.investopedia.com/terms/m/marketcapitalization.asp class="btn btn-outline-success"></button> Keep learning! </a></p></li>
        <li><p>Book Value Per Share. (Bvps) <a href =https://www.investopedia.com/terms/b/bvps.asp class="btn btn-outline-success"></button> Keep learning! </a></p></li>
        <li><p>Price To Book  <a href =https://www.investopedia.com/terms/p/price-to-bookratio.asp class="btn btn-outline-success"></button> Keep learning! </a></p></li>
    </ul>
    <br>
    <p>Add companies to your portfolio to evaluate them <a href ="{% url 'simple_investing:create_company' %}" class="btn btn-success"></button>Click!</a></p>
{% endblock content %}


mysite/simple_investing/templates/simple_investing/create_company.html
{% extends 'simple_investing/base.html' %}
{% block subtitle %} Add a company to your portfolio {%endblock subtitle%}
{% block content %}    
    <hr>
    {% if user.is_authenticated %}   
        <p>In this section, you will be able to add a company to your portfolio and have access to its fundamentals.The goal is to assess if the <strong><i>stock market</i></strong> is offering us an investment opportunity. </p>
        <p>Let's start by entering the data of the company that you are interested in: </p>        
        <div class="row g-3">                  
            <form action ="" method="post">
                {% csrf_token %}
                {{form.as_p}}
                <button type="submit" class="btn btn-success">Submit</button> 
            </form>
        </div>   
    {% else %}
        <p>In order to use our amazing tool <a href = "/accounts/login/">login here</a></p>
    {% endif %}
{% endblock content %}    



mysite/simple_investing/templates/simple_investing/delete_company.html
{% extends 'simple_investing/base.html' %}
{% block content %}
    <form action="" method="post">
        {% csrf_token %}
        <p> Do you want to <b>delete</b> {{company}} from your portfolio?</p>            
        <p><button type="submit" class="btn btn-outline-danger">Delete</button></p>
        <p><a href="{% url 'simple_investing:create_company'%}"class="btn btn-outline-success">Go back</a></p>
    </form>
{% endblock content %}

mysite/simple_investing/templates/simple_investing/detail.html
{% extends 'simple_investing/base.html' %}
{% block content %}
   {%if company.user == user%}    
    <h2 class="company display-4" style="text-align: center;">{{company}}</h2>  
    <hr>
    <br>
    <div>
        <table class="table table-bordered">
            <thead>
                <tr class="table-success">
                    <th>Outstanding Shares</th>
                    <th>Share Price</th>
                    <th>Revenue</th>
                    <th>Expenses</th>
                    <th>Total Liabilities</th>
                    <th>Total Assets</th>
                    <th>Current Assets</th>
                    <th>Current Liabilities</th>
                    <th>Operating Cashflows</th>
                    <th>Capital Expenditure</th>                
                </tr>
            </thead>   
            <tbody>
                <tr>
                    <td>{{company.outstanding_shares}}</td>
                    <td>{{company.share_price}}</td>
                    <td>{{company.revenue}}</td>
                    <td>{{company.expenses}}</td>
                    <td>{{company.total_liabilities}}</td>
                    <td>{{company.total_assets}}</td>
                    <td>{{company.current_assets}}</td>
                    <td>{{company.current_liabilities}}</td>
                    <td>{{company.operating_cashflows}}</td>
                    <td>{{company.capex}}</td>
                                       
                </tr>
            </tbody>
        </table>
    </div>
    <p>According to the information you enter, these are the fundamentals of {{company}}:</p>
    <p>
        <ul class="list-group" style="width: max-content;">
            <li class="list-group-item">Net income: <b>{{company.net_income}}</b></li>
            <li class="list-group-item">Net assets/Shareholders equity: <b>{{company.net_assets}}</b></li>
            <li class="list-group-item">Return on equity: <b>{{company.return_on_equity}}</b></li>
            <li class="list-group-item">Price to earnings: <b>{{company.price_to_earnings}}</b></li>
            <li class="list-group-item">Debt to equity: <b>{{company.debt_to_equity}}</b></li>
            <li class="list-group-item">Current Ratio: <b>{{company.current_ratio}}</b></li>
            <li class="list-group-item">Free cashflow: <b>{{company.current_ratio}}</b></li> 
            <li class="list-group-item">Market Capitalization:<b>{{company.market_cap}}</b></li>
            <li class="list-group-item">Price to sales: <b>{{company.price_to_sales}}</b></li>
            <li class="list-group-item">Book Value Per Share: <b>{{company.book_value_per_share}}</b></li>
            <li class="list-group-item">Price to book: <b>{{company.price_to_book}}</b></li>
        </ul>   
    </p>  
    <p><a href= "{% url 'simple_investing:update_company' company.id %}" class="btn btn-outline-success"></button>Update</a></p>    
    <p><a href ="{% url 'simple_investing:symbol'%}" class="btn btn-outline-success"></button> Compare results with Yahoo</a></p>
    <p><a href='http://127.0.0.1:8000/concepts' class="btn btn-outline-success"></button> Revise concepts </a></p>
    <a href= "{% url 'simple_investing:delete_company' company.id%}" class="btn btn-outline-danger"></button> Delete</a></p> 
    
    <p>If price to earnings is below 15 and price to book is less than 1.5, it could represent a good buying opportunity. 
    <p>Return on equity is consider to be good when it's above 15 points and when it has been increasing overtime.</p>
    <p> Free cashflow is an important metric, the higher the number the better.</p>
    <p>Bare in mind that ratio results differ with each industry.</p>
    <p>Remember that these numbers are providing past information, as investors we try to read into the future and see what the numbers will be like in 2, 3, 10 years from now.</p>    
    {%else%}
        <p>You don't have acces to this page, you can go back to your <a href ="{% url 'simple_investing:companies_list' %}">porfolio</a></p>

    {%endif%}
{% endblock content %}

mysite/simple_investing/templates/simple_investing/main.html
{% extends 'simple_investing/base.html' %}    
{% block subtitle %} Welcome to Simple Investing {% endblock subtitle %}
{%block content%}
    <hr>
    <br>
    <p style = "font-style: normal">This website has the goal of assisting <strong><em>you</em></strong> in the process of making <strong><em>sound investment decisions</em></strong> in the <i>stock market</i>. In order to accomplish this goal we focus on:</p> 
    <ul>
        <li><p> Basic concepts that everyone should know before making an investment.</p></li>
        <li><p> Providing the tools necessary to analyze the fundamentals of any public company. 
    </ul>
    <p>You will be able to create a portfolio of public companies that you are interested in. In order to do so, you will have to insert data available in the anual reports of each company.</p> 
    <p> If you do not want to do the research, you have the option to access the data by entering the ticker <a href= 'https://www.investopedia.com/terms/s/stocksymbol.asp'>symbol</a> of the company you are interested in. Just press on the following <a href="{% url 'simple_investing:symbol'%}">link.</a></p>
    <p>Weighing which option is better for you will depend on whether you trust a third party to run the numbers for you or if you are a do it yourself person.</p>    
    <p>In order to get the data directly of each company we use Yahoo finance API.</p>
    <p>Let's start by learning the main <a href ="http://127.0.0.1:8000/concepts">concepts.</a></p>
    <p>If you already have a foundation on the matter, you can start by <a href = "{% url 'simple_investing:create_company' %}">adding</a> companies to your portfolio to evaluate them.</p>

{% endblock content%}


mysite/simple_investing/templates/simple_investing/register.html
{% extends 'simple_investing/base.html' %}
<br>
<hr>
<br>
{% block content %}
<p>Sign up and have access to our tools.</p>


<form action= "" method="post">
    {% csrf_token %}
    {{ form.non_field_errors }}
    {% for field in form %}
      <p>
        {{ field.label }}
        {{ field }}
        {{ field.errors }}
      </p>
    {% endfor %}
    <button type="submit" class="btn btn-success">Create User</button>
  </form>

{% endblock content %}

mysite/simple_investing/templates/simple_investing/symbol.html
{% extends 'simple_investing/base.html' %}
{% block subtitle %} Tycker Symbol {% endblock subtitle %}
{% block content %}    
    <hr>
    <p>In this section you will be able to look up for any public traded company using its stock symbol. Once you find it, submit it and get all the important data.</p>
    <br>
    {% if user.is_authenticated %}
        <p>If you wish to do the research yourself and insert the data just gather <a href="{% url 'simple_investing:create_company' %}">click.</a></p>    
        <form action="/symbol/" method="post">
            {% csrf_token %}
            {{form.as_p}}       
         <button type="submit" class="btn btn-success">Submit</button>
        </form>
    {% else %}
        <p>In order to use our amazing tool <a href = "/accounts/login/">login here</a></p>
    {% endif %}
{%endblock content %}  


mysite/simple_investing/templates/simple_investing/yahoo_api.html
{% extends 'simple_investing/base.html' %}
{% block content %}
{%if is_company == True %}
    <h2 class = "display-6" style="text-align: center;">{{company.displayName}}'s fundamentals:</h2>    
    <hr>
    <br>
    <br>
    <ul class="list-group" style="width: max-content;">
        <li class="list-group-item">Current market price: {{company.regularMarketPrice}}</l>
        <li class="list-group-item">52 week high: {{company.fiftyTwoWeekHigh}}</li>
        <li class="list-group-item">52 week high: {{company.fiftyTwoWeekLow}} </li>
        <li class="list-group-item">Currency: {{company.currency}}</li>       
        <li class="list-group-item">Market: {{company.market}}</li>        
        <li class="list-group-item">Company Market Capitalization: {{company.marketCap}}</li>
        <li class="list-group-item">Company outstanding shares: {{company.sharesOutstanding}}</li>
        <li class="list-group-item">Current book value: {{company.bookValue}}</li>
        <li class="list-group-item">Earnings per share for the year: {{company.epsCurrentYear}}</li>
        <li class="list-group-item">Forward earnings per share: {{company.epsForward}}</li>
        <li class="list-group-item">Trailing EPS, 12 months: {{company.epsTrailingTwelveMonths}}</li>
    </ul>
    <br>
    <p style='text-align: center;'><a href= "{% url 'simple_investing:symbol' %}"  class="btn btn-outline-success">Look for another company </a></p>
 {%else%}
    <p>The ticker symbol you entered is incorrect. Double check the symbol and re-enter it.</p>
    <p><a href= "{% url 'simple_investing:symbol' %}"  class="btn btn-outline-success">Tycker symbol </a></p></p> 
{%endif%}
 {%endblock content %}   